server:
  port: 8080
spring:

  servlet:
    multipart:
      maxFileSize: 5MB
  application:
    name: douyin
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.113.194.17:3306/douyin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Xmut2615@
      mysql:
        usePingMethod=false:
mybatis-plus:
  configuration:
    #???????????????????????????????????????
    map-underscore-to-camel-case: false
  #    mybatis????
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: D:/tmp/douyin/

